name: 'Delete Empty Codespaces'
author: 'NickLiffen'
description: 'An action which deletes codespaces for an authenticated user where there are no uncommitted changes.'
inputs:
  GITHUB_TOKEN:
    description: 'A GitHub token with the codespaces scope'
    required: false
outputs:
  success:
    description: 'true|false based on if the script worked'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'target'  
  color: 'blue'