--- 
jobs: 
  regression: 
    name: regression
    runs-on: ubuntu-20.04
    steps: 
      - 
        name: Git Checkout
        uses: actions/checkout@v4
        with: 
          path: regression
      - 
        name: Test Action
        uses: ./regression
        id: regression
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      -
        run: |
          echo "${{ steps.regression.outputs.success }}"

name: "Regression Testing"
? "on"
: 
  workflow_dispatch: 
    inputs: 
      exampleInput: 
        default: xys
        description: "xyz"
        required: true